# Credit Card Database with Affiliate Links
# Starting with 15 working cards, will expand via admin interface

CREDIT_CARDS_DATABASE = [
    {
        "id": "hdfc-infinia",
        "bank_name": "HDFC Bank",
        "card_name": "Infinia",
        "card_type": "premium",
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points + complimentary Club Marriott membership",
        "reward_rate": 3.3,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Apple products", "Smartbuy", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["10,000 points on ₹8L annual spend"],
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "forex_markup": 2.0,
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.3, "shopping": 3.3},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-infinia-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-infinia-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-infinia/"
    },
    {
        "id": "hdfc-regalia-gold",
        "bank_name": "HDFC Bank",
        "card_name": "Regalia Gold",
        "card_type": "premium",
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.5,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.7,
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "reward_cap_monthly": 15000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["4,000 points on ₹3L annual spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 2.0,
        "lounge_access": "12 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 100000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 4.0, "dining": 2.5, "shopping": 2.5},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-regalia-gold-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-regalia-gold-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-regalia/"
    },
    {
        "id": "sbi-simplyclick",
        "bank_name": "SBI Card",
        "card_name": "SimplyCLICK",
        "card_type": "cashback",
        "joining_fee": 499,
        "annual_fee": 499,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 Amazon voucher",
        "reward_rate": 1.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Amazon vouchers", "Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"online_shopping": 10.0, "dining": 1.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/sbi-simplyclick-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-simplyclick-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/sbi-simplyclick/"
    },
    {
        "id": "icici-amazon-pay",
        "bank_name": "ICICI Bank",
        "card_name": "Amazon Pay",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 Amazon voucher on first transaction",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Amazon Pay balance"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": 15000,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent", "EMI"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"amazon": 5.0, "online_shopping": 2.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/icici-amazon-pay-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/icici-amazon-pay-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/icici-amazon-pay/"
    },
    {
        "id": "axis-magnus",
        "bank_name": "Axis Bank",
        "card_name": "Magnus",
        "card_type": "premium",
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "welcome_benefits": "25,000 Edge Reward points",
        "reward_rate": 12.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Vouchers", "Airmiles"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["25,000 points on ₹15L annual spend"],
        "excluded_categories": ["Fuel", "Rent"],
        "forex_markup": 2.0,
        "lounge_access": "Unlimited domestic & 8 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 12.0, "dining": 12.0, "shopping": 6.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/axis-magnus-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/axis-magnus-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/axis-magnus/"
    },
    {
        "id": "amex-platinum",
        "bank_name": "American Express",
        "card_name": "Platinum Card",
        "card_type": "premium",
        "joining_fee": 60000,
        "annual_fee": 60000,
        "is_lifetime_free": False,
        "welcome_benefits": "Taj voucher worth ₹10,000 + Airport transfers",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Travel", "Hotels", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Taj vouchers on milestone spend"],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "Unlimited domestic & international + guest + Centurion lounges",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 500000,
        "min_credit_score": 800,
        "category_bonuses": {"travel": 5.0, "dining": 2.0, "hotels": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/american-express-platinum-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/american-express-platinum-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/amex-platinum/"
    },
    {
        "id": "axis-ace",
        "bank_name": "Axis Bank",
        "card_name": "Ace",
        "card_type": "lifetime_free",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 cashback on ₹10,000 spend in 45 days",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": 15000,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent", "Wallet loads"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 20000,
        "min_credit_score": 600,
        "category_bonuses": {"google_pay": 5.0, "utilities": 2.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/axis-ace-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/axis-ace-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/axis-ace/"
    },
    {
        "id": "indusind-legend",
        "bank_name": "IndusInd Bank",
        "card_name": "Legend",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "₹25,000 welcome vouchers + Golf rounds",
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹8L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.75,
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 200000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.0, "shopping": 3.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/indusind-legend-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/indusind-legend-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sc-ultimate",
        "bank_name": "Standard Chartered",
        "card_name": "Ultimate",
        "card_type": "premium",
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points",
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.8,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹4L spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 150000,
        "min_credit_score": 720,
        "category_bonuses": {"travel": 5.0, "dining": 5.0, "shopping": 1.5},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/standard-chartered-ultimate-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/standard-chartered-ultimate-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "hsbc-cashback",
        "bank_name": "HSBC",
        "card_name": "Cashback",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 cashback on first transaction",
        "reward_rate": 0.0,
        "cashback_rate": 10.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 1000,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": False,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"online_shopping": 10.0, "groceries": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hsbc-cashback-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hsbc-cashback-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "kotak-white-reserve",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "White Reserve",
        "card_type": "premium",
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee reversal on ₹4L spend"],
        "excluded_categories": ["Fuel", "Rent"],
        "forex_markup": 2.5,
        "lounge_access": "8 domestic & 4 international per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 120000,
        "min_credit_score": 700,
        "category_bonuses": {"dining": 4.0, "travel": 3.0, "shopping": 2.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/kotak-white-reserve-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/kotak-white-reserve-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "citi-rewards",
        "bank_name": "Citi Bank",
        "card_name": "Rewards",
        "card_type": "lifestyle",
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "welcome_benefits": "2,500 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit", "Products"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 80000,
        "min_credit_score": 680,
        "category_bonuses": {"dining": 5.0, "shopping": 2.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/citi-rewards-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/citi-rewards-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "yes-marquee",
        "bank_name": "Yes Bank",
        "card_name": "Marquee",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "Club Vistara Gold membership",
        "reward_rate": 6.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Airmiles", "Statement credit", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["₹10,000 voucher on ₹8L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.75,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 12.0, "dining": 6.0, "shopping": 3.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/yes-bank-marquee-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/yes-bank-marquee-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "rbl-shoprite",
        "bank_name": "RBL Bank",
        "card_name": "Shoprite",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 gift voucher",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"groceries": 10.0, "dining": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/rbl-shoprite-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/rbl-shoprite-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "federal-celesta",
        "bank_name": "Federal Bank",
        "card_name": "Celesta",
        "card_type": "travel",
        "joining_fee": 1500,
        "annual_fee": 1500,
        "is_lifetime_free": False,
        "welcome_benefits": "2 complimentary movie tickets",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹2L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.0,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 60000,
        "min_credit_score": 680,
        "category_bonuses": {"travel": 4.0, "dining": 2.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/federal-celesta-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/federal-celesta-credit-card.html",
        "paisabazaar_link": None
    }
]
