# Comprehensive Indian Credit Card Database - 50+ Cards
# Complete with affiliate links for BankBazaar and Paisabazaar

CREDIT_CARDS_DATABASE = [
    # HDFC Bank Cards (7 cards)
    {
        "id": "hdfc-infinia",
        "bank_name": "HDFC Bank",
        "card_name": "Infinia",
        "card_type": "premium",
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points + complimentary Club Marriott membership",
        "reward_rate": 3.3,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Apple products", "Smartbuy", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["10,000 points on ₹8L annual spend"],
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "forex_markup": 2.0,
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.3, "shopping": 3.3},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-infinia-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-infinia/"
    },
    {
        "id": "hdfc-regalia-gold",
        "bank_name": "HDFC Bank",
        "card_name": "Regalia Gold",
        "card_type": "premium",
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.5,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.7,
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "reward_cap_monthly": 15000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["4,000 points on ₹3L annual spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 2.0,
        "lounge_access": "12 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 100000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 4.0, "dining": 2.5, "shopping": 2.5},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-regalia-gold-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-regalia/"
    },
    {
        "id": "hdfc-millennia",
        "bank_name": "HDFC Bank",
        "card_name": "Millennia",
        "card_type": "lifestyle",
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "welcome_benefits": "1,000 cashback points",
        "reward_rate": 2.5,
        "cashback_rate": 5.0,
        "redemption_ratio": 0.3,
        "redemption_options": ["Cashback", "Vouchers"],
        "reward_cap_monthly": 1000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 2.0,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"online_shopping": 5.0, "groceries": 2.5},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/millennia-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-millennia-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-millennia/"
    },
    {
        "id": "hdfc-freedom",
        "bank_name": "HDFC Bank",
        "card_name": "Freedom",
        "card_type": "cashback",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 cashback",
        "reward_rate": 0.0,
        "cashback_rate": 1.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹50K spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.0,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"all": 1.0},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/freedom-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-freedom-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "hdfc-moneyback",
        "bank_name": "HDFC Bank",
        "card_name": "MoneyBack",
        "card_type": "cashback",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 welcome voucher",
        "reward_rate": 0.0,
        "cashback_rate": 2.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹50K annual spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"dining": 5.0, "groceries": 2.0},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/moneyback-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-moneyback-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "hdfc-bizblack",
        "bank_name": "HDFC Bank",
        "card_name": "BizBlack",
        "card_type": "business",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "15,000 reward points",
        "reward_rate": 4.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["10,000 bonus points on ₹8L annual spend"],
        "excluded_categories": [],
        "forex_markup": 1.99,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 200000,
        "min_credit_score": 750,
        "category_bonuses": {"business": 4.0, "travel": 5.0},
        "affiliate_link": "https://www.hdfcbank.com/business/pay/cards/bizblack-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bizblack-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "hdfc-diners-black",
        "bank_name": "HDFC Bank",
        "card_name": "Diners Club Black",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points + Priority Pass",
        "reward_rate": 3.3,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Vouchers", "Airmiles"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹5L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.99,
        "lounge_access": "Unlimited domestic & international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 200000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.3},
        "affiliate_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/diners-black-credit-card",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # SBI Card (Already had 1, adding 5 more = 6 total)
    {
        "id": "sbi-simplyclick",
        "bank_name": "SBI Card",
        "card_name": "SimplyCLICK",
        "card_type": "cashback",
        "joining_fee": 499,
        "annual_fee": 499,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 Amazon voucher",
        "reward_rate": 1.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Amazon vouchers", "Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"online_shopping": 10.0, "dining": 1.0},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/shopping/simplyclick-sbi-card.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-simplyclick-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/sbi-simplyclick/"
    },
    {
        "id": "sbi-elite",
        "bank_name": "SBI Card",
        "card_name": "Elite",
        "card_type": "premium",
        "joining_fee": 4999,
        "annual_fee": 4999,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Airmiles", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹5L spend", "5,000 bonus points on ₹5L"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.5,
        "lounge_access": "8 domestic & 4 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 120000,
        "min_credit_score": 720,
        "category_bonuses": {"travel": 4.0, "dining": 2.0, "shopping": 1.5},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/travel/elite-credit-card.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-elite-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sbi-prime",
        "bank_name": "SBI Card",
        "card_name": "Prime",
        "card_type": "lifestyle",
        "joining_fee": 2999,
        "annual_fee": 2999,
        "is_lifetime_free": False,
        "welcome_benefits": "3,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": 10000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹3L annual spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 70000,
        "min_credit_score": 700,
        "category_bonuses": {"dining": 5.0, "movies": 5.0, "shopping": 1.5},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/lifestyle/prime-credit-card.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-prime-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sbi-cashback",
        "bank_name": "SBI Card",
        "card_name": "Cashback",
        "card_type": "cashback",
        "joining_fee": 999,
        "annual_fee": 999,
        "is_lifetime_free": False,
        "welcome_benefits": "₹2,000 cashback",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹2L spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 680,
        "category_bonuses": {"online_shopping": 5.0, "groceries": 5.0},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/cashback/cashback-sbi-card.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-cashback-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sbi-simplysa VE",
        "bank_name": "SBI Card",
        "card_name": "SimplySAVE",
        "card_type": "lifetime_free",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "Welcome e-gift voucher worth ₹2,000",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"groceries": 10.0, "dining": 5.0},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/shopping/simplysave-sbi-card.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-simplysave-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sbi-octane",
        "bank_name": "SBI Card",
        "card_name": "BPCL Octane",
        "card_type": "fuel",
        "joining_fee": 1499,
        "annual_fee": 1499,
        "is_lifetime_free": False,
        "welcome_benefits": "1,500 fuel points",
        "reward_rate": 0.0,
        "cashback_rate": 7.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Fuel", "Statement credit"],
        "reward_cap_monthly": 500,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1.5L spend"],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 40000,
        "min_credit_score": 680,
        "category_bonuses": {"fuel": 7.0, "groceries": 1.0},
        "affiliate_link": "https://www.sbicard.com/en/personal/credit-cards/fuel/bpcl-sbi-card-octane.page",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/sbi-bpcl-octane-credit-card.html",
        "paisabazaar_link": None
    },

    # ICICI Bank Cards (Already had 1, adding 5 more = 6 total)
    {
        \"id\": \"icici-amazon-pay\",
        \"bank_name\": \"ICICI Bank\",
        \"card_name\": \"Amazon Pay\",
        \"card_type\": \"cashback\",
        \"joining_fee\": 0,
        \"annual_fee\": 0,
        \"is_lifetime_free\": True,
        \"welcome_benefits\": \"\u20b9500 Amazon voucher on first transaction\",
        \"reward_rate\": 0.0,
        \"cashback_rate\": 5.0,
        \"redemption_ratio\": 1.0,
        \"redemption_options\": [\"Amazon Pay balance\"],
        \"reward_cap_monthly\": None,
        \"reward_cap_yearly\": 15000,
        \"milestone_benefits\": [],
        \"excluded_categories\": [\"Fuel\", \"Rent\", \"EMI\"],
        \"forex_markup\": 3.5,
        \"lounge_access\": \"None\",
        \"fuel_surcharge_waiver\": True,
        \"emi_available\": True,
        \"min_income\": 25000,
        \"min_credit_score\": 650,
        \"category_bonuses\": {\"amazon\": 5.0, \"online_shopping\": 2.0},
        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/amazon-pay-credit-card\",
        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-amazon-pay-credit-card.html\",\n        \"paisabazaar_link\": \"https://www.paisabazaar.com/credit-card/icici-amazon-pay/\"\n    },
    {
        \"id\": \"icici-sapphiro\",
        \"bank_name\": \"ICICI Bank\",
        \"card_name\": \"Sapphiro\",\n        \"card_type\": \"premium\",\n        \"joining_fee\": 3500,\n        \"annual_fee\": 3500,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"2,000 bonus reward points\",\n        \"reward_rate\": 2.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Airmiles\", \"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b94L annual spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"8 domestic & 4 international\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 100000,\n        \"min_credit_score\": 720,\n        \"category_bonuses\": {\"travel\": 4.0, \"dining\": 2.0},\n        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/sapphiro-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-sapphiro-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"icici-coral\",\n        \"bank_name\": \"ICICI Bank\",\n        \"card_name\": \"Coral\",\n        \"card_type\": \"lifestyle\",\n        \"joining_fee\": 500,\n        \"annual_fee\": 500,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"500 reward points\",\n        \"reward_rate\": 2.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b950K annual spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 35000,\n        \"min_credit_score\": 680,\n        \"category_bonuses\": {\"dining\": 4.0, \"movies\": 4.0},\n        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/coral-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-coral-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"icici-rubyx\",\n        \"bank_name\": \"ICICI Bank\",\n        \"card_name\": \"Rubyx\",\n        \"card_type\": \"lifestyle\",\n        \"joining_fee\": 3000,\n        \"annual_fee\": 3000,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"2,500 reward points\",\n        \"reward_rate\": 2.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Airmiles\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b93L spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"4 domestic per year\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 60000,\n        \"min_credit_score\": 700,\n        \"category_bonuses\": {\"dining\": 4.0, \"shopping\": 2.0},\n        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/rubyx-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-rubyx-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"icici-platinum\",\n        \"bank_name\": \"ICICI Bank\",\n        \"card_name\": \"Platinum\",\n        \"card_type\": \"lifestyle\",\n        \"joining_fee\": 0,\n        \"annual_fee\": 0,\n        \"is_lifetime_free\": True,\n        \"welcome_benefits\": \"Welcome voucher worth \u20b9500\",\n        \"reward_rate\": 1.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 30000,\n        \"min_credit_score\": 650,\n        \"category_bonuses\": {\"dining\": 2.0, \"shopping\": 1.0},\n        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/platinum-chip-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-platinum-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"icici-hpcl\",\n        \"bank_name\": \"ICICI Bank\",\n        \"card_name\": \"HPCL Coral\",\n        \"card_type\": \"fuel\",\n        \"joining_fee\": 500,\n        \"annual_fee\": 500,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"500 fuel points\",\n        \"reward_rate\": 0.0,\n        \"cashback_rate\": 5.0,\n        \"redemption_ratio\": 1.0,\n        \"redemption_options\": [\"Fuel\", \"Statement credit\"],\n        \"reward_cap_monthly\": 250,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b950K spend\"],\n        \"excluded_categories\": [],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 30000,\n        \"min_credit_score\": 680,\n        \"category_bonuses\": {\"fuel\": 5.0},\n        \"affiliate_link\": \"https://www.icicibank.com/personal-banking/cards/credit-card/hpcl-coral-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/icici-hpcl-coral-credit-card.html\",\n        \"paisabazaar_link\": None\n    },\n\n    # Axis Bank Cards (Already had 2, adding 4 more = 6 total)
    {
        \"id\": \"axis-magnus\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"Magnus\",\n        \"card_type\": \"premium\",\n        \"joining_fee\": 12500,\n        \"annual_fee\": 12500,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"25,000 Edge Reward points\",\n        \"reward_rate\": 12.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 1.0,\n        \"redemption_options\": [\"Travel\", \"Vouchers\", \"Airmiles\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"25,000 points on \u20b915L annual spend\"],\n        \"excluded_categories\": [\"Fuel\", \"Rent\"],\n        \"forex_markup\": 2.0,\n        \"lounge_access\": \"Unlimited domestic & 8 international\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 250000,\n        \"min_credit_score\": 750,\n        \"category_bonuses\": {\"travel\": 12.0, \"dining\": 12.0, \"shopping\": 6.0},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-magnus-credit-card.html\",\n        \"paisabazaar_link\": \"https://www.paisabazaar.com/credit-card/axis-magnus/\"\n    },
    {
        \"id\": \"axis-ace\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"Ace\",\n        \"card_type\": \"lifetime_free\",\n        \"joining_fee\": 0,\n        \"annual_fee\": 0,\n        \"is_lifetime_free\": True,\n        \"welcome_benefits\": \"\u20b9500 cashback on \u20b910,000 spend in 45 days\",\n        \"reward_rate\": 0.0,\n        \"cashback_rate\": 5.0,\n        \"redemption_ratio\": 1.0,\n        \"redemption_options\": [\"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": 15000,\n        \"milestone_benefits\": [],\n        \"excluded_categories\": [\"Fuel\", \"Rent\", \"Wallet loads\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 20000,\n        \"min_credit_score\": 600,\n        \"category_bonuses\": {\"google_pay\": 5.0, \"utilities\": 2.0},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/axis-bank-ace-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-ace-credit-card.html\",\n        \"paisabazaar_link\": \"https://www.paisabazaar.com/credit-card/axis-ace/\"\n    },
    {
        \"id\": \"axis-my-zone\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"My Zone\",\n        \"card_type\": \"lifestyle\",\n        \"joining_fee\": 500,\n        \"annual_fee\": 500,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"\u20b9500 voucher\",\n        \"reward_rate\": 2.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b91L annual spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 30000,\n        \"min_credit_score\": 650,\n        \"category_bonuses\": {\"dining\": 4.0, \"movies\": 4.0, \"shopping\": 1.5},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/my-zone-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-my-zone-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"axis-flipkart\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"Flipkart\",\n        \"card_type\": \"cashback\",\n        \"joining_fee\": 0,\n        \"annual_fee\": 0,\n        \"is_lifetime_free\": True,\n        \"welcome_benefits\": \"\u20b9500 gift card on first transaction\",\n        \"reward_rate\": 0.0,\n        \"cashback_rate\": 5.0,\n        \"redemption_ratio\": 1.0,\n        \"redemption_options\": [\"Flipkart vouchers\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": 15000,\n        \"milestone_benefits\": [],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"None\",\n        \"fuel_surcharge_waiver\": False,\n        \"emi_available\": True,\n        \"min_income\": 25000,\n        \"min_credit_score\": 650,\n        \"category_bonuses\": {\"flipkart\": 5.0, \"online_shopping\": 1.5},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/axis-bank-flipkart-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-flipkart-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"axis-select\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"Select\",\n        \"card_type\": \"premium\",\n        \"joining_fee\": 3000,\n        \"annual_fee\": 3000,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"5,000 Edge Reward points\",\n        \"reward_rate\": 2.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 0.25,\n        \"redemption_options\": [\"Vouchers\", \"Airmiles\", \"Statement credit\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"Fee waiver on \u20b93L spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 3.5,\n        \"lounge_access\": \"4 domestic per year\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 80000,\n        \"min_credit_score\": 700,\n        \"category_bonuses\": {\"travel\": 4.0, \"dining\": 2.0},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/select-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-select-credit-card.html\",\n        \"paisabazaar_link\": None\n    },
    {
        \"id\": \"axis-vistara\",\n        \"bank_name\": \"Axis Bank\",\n        \"card_name\": \"Vistara Infinite\",\n        \"card_type\": \"travel\",\n        \"joining_fee\": 10000,\n        \"annual_fee\": 10000,\n        \"is_lifetime_free\": False,\n        \"welcome_benefits\": \"Club Vistara Gold membership\",\n        \"reward_rate\": 6.0,\n        \"cashback_rate\": 0.0,\n        \"redemption_ratio\": 1.0,\n        \"redemption_options\": [\"Vistara miles\", \"Airmiles\"],\n        \"reward_cap_monthly\": None,\n        \"reward_cap_yearly\": None,\n        \"milestone_benefits\": [\"4,000 miles on \u20b94L spend\"],\n        \"excluded_categories\": [\"Fuel\"],\n        \"forex_markup\": 2.0,\n        \"lounge_access\": \"Unlimited domestic & 8 international\",\n        \"fuel_surcharge_waiver\": True,\n        \"emi_available\": True,\n        \"min_income\": 200000,\n        \"min_credit_score\": 750,\n        \"category_bonuses\": {\"travel\": 10.0, \"dining\": 4.0},\n        \"affiliate_link\": \"https://www.axisbank.com/retail/cards/credit-card/vistara-credit-card\",\n        \"bankbazaar_link\": \"https://www.bankbazaar.com/credit-card/axis-vistara-infinite-credit-card.html\",\n        \"paisabazaar_link\": None\n    }\n]\n\n# American Express Cards (5 cards)
    {
        "id": "amex-platinum",
        "bank_name": "American Express",
        "card_name": "Platinum Card",
        "card_type": "premium",
        "joining_fee": 60000,
        "annual_fee": 60000,
        "is_lifetime_free": False,
        "welcome_benefits": "Taj voucher worth ₹10,000 + Airport transfers",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Travel", "Hotels", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Taj vouchers on milestone spend"],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "Unlimited domestic & international + guest + Centurion lounges",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 500000,
        "min_credit_score": 800,
        "category_bonuses": {"travel": 5.0, "dining": 2.0, "hotels": 5.0},
        "affiliate_link": "https://www.americanexpress.com/in/credit-cards/platinum-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/american-express-platinum-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/amex-platinum/"
    },
    {
        "id": "amex-gold",
        "bank_name": "American Express",
        "card_name": "Gold Card",
        "card_type": "premium",
        "joining_fee": 4500,
        "annual_fee": 4500,
        "is_lifetime_free": False,
        "welcome_benefits": "4,000 bonus points + Taj voucher",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1.5L annual spend"],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "8 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 90000,
        "min_credit_score": 720,
        "category_bonuses": {"travel": 4.0, "dining": 3.0},
        "affiliate_link": "https://www.americanexpress.com/in/credit-cards/gold-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/american-express-gold-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "amex-membership-rewards",
        "bank_name": "American Express",
        "card_name": "Membership Rewards",
        "card_type": "lifestyle",
        "joining_fee": 1500,
        "annual_fee": 1500,
        "is_lifetime_free": False,
        "welcome_benefits": "2,000 bonus points",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Vouchers", "Travel", "Products"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹90K annual spend"],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"dining": 2.0, "shopping": 1.0},
        "affiliate_link": "https://www.americanexpress.com/in/credit-cards/membership-rewards-credit-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/american-express-membership-rewards-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "amex-smartearn",
        "bank_name": "American Express",
        "card_name": "SmartEarn",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "2,000 bonus points on ₹5,000 spend in 60 days",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Statement credit", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": 30000,
        "milestone_benefits": [],
        "excluded_categories": [],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 680,
        "category_bonuses": {"online_shopping": 5.0, "groceries": 1.5},
        "affiliate_link": "https://www.americanexpress.com/in/credit-cards/smart-earn-credit-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/american-express-smartearn-card.html",
        "paisabazaar_link": None
    },

    # Kotak Mahindra Bank Cards (Already had 1, adding 4 more = 5 total)
    {
        "id": "kotak-white-reserve",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "White Reserve",
        "card_type": "premium",
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee reversal on ₹4L spend"],
        "excluded_categories": ["Fuel", "Rent"],
        "forex_markup": 2.5,
        "lounge_access": "8 domestic & 4 international per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 120000,
        "min_credit_score": 700,
        "category_bonuses": {"dining": 4.0, "travel": 3.0, "shopping": 2.0},
        "affiliate_link": "https://www.kotak.com/en/personal-banking/cards/credit-cards/kotak-white-reserve-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/kotak-white-reserve-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "kotak-811",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "811 #DreamDifferent",
        "card_type": "lifetime_free",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "PVR voucher worth ₹500",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"dining": 4.0, "shopping": 1.0},
        "affiliate_link": "https://www.kotak.com/en/personal-banking/cards/credit-cards/kotak-811-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/kotak-811-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "kotak-myntra",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "Myntra Kotak Card",
        "card_type": "lifestyle",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 Myntra voucher",
        "reward_rate": 0.0,
        "cashback_rate": 10.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Myntra vouchers"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L annual spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"myntra": 20.0, "fashion": 5.0},
        "affiliate_link": "https://www.kotak.com/en/personal-banking/cards/credit-cards/myntra-kotak-credit-card.html",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },
    {
        "id": "kotak-league-platinum",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "League Platinum",
        "card_type": "lifestyle",
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "welcome_benefits": "1,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 40000,
        "min_credit_score": 680,
        "category_bonuses": {"dining": 4.0, "shopping": 2.0},
        "affiliate_link": "https://www.kotak.com/en/personal-banking/cards/credit-cards/kotak-league-platinum-credit-card.html",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # IndusInd Bank Cards (Already had 1, adding 3 more = 4 total)
    {
        "id": "indusind-legend",
        "bank_name": "IndusInd Bank",
        "card_name": "Legend",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "₹25,000 welcome vouchers + Golf rounds",
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹8L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.75,
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 200000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.0, "shopping": 3.0},
        "affiliate_link": "https://www.indusind.com/in/en/personal/cards/credit-card/indusind-legend-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/indusind-legend-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "indusind-pinnacle",
        "bank_name": "IndusInd Bank",
        "card_name": "Pinnacle",
        "card_type": "premium",
        "joining_fee": 3000,
        "annual_fee": 3000,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Vouchers", "Airmiles", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.5,
        "lounge_access": "8 domestic & 4 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 80000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 4.0, "dining": 2.5},
        "affiliate_link": "https://www.indusind.com/in/en/personal/cards/credit-card/indusind-pinnacle-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/indusind-pinnacle-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "indusind-eazydiner",
        "bank_name": "IndusInd Bank",
        "card_name": "EazyDiner Indus Exclusive",
        "card_type": "lifestyle",
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹5,000 dining vouchers",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Dining vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹2.5L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 60000,
        "min_credit_score": 700,
        "category_bonuses": {"dining": 10.0, "travel": 2.0},
        "affiliate_link": "https://www.indusind.com/in/en/personal/cards/credit-card/eazydiner-indusind-bank-credit-card.html",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # Standard Chartered Cards (Already had 1, adding 3 more = 4 total)
    {
        "id": "sc-ultimate",
        "bank_name": "Standard Chartered",
        "card_name": "Ultimate",
        "card_type": "premium",
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points",
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.8,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹4L spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 150000,
        "min_credit_score": 720,
        "category_bonuses": {"travel": 5.0, "dining": 5.0, "shopping": 1.5},
        "affiliate_link": "https://www.sc.com/in/credit-cards/ultimate-credit-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/standard-chartered-ultimate-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sc-manhattan",
        "bank_name": "Standard Chartered",
        "card_name": "Manhattan",
        "card_type": "premium",
        "joining_fee": 999,
        "annual_fee": 999,
        "is_lifetime_free": False,
        "welcome_benefits": "2,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Vouchers", "Airmiles"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1.5L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 3.0, "dining": 2.0},
        "affiliate_link": "https://www.sc.com/in/credit-cards/manhattan-credit-card/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/standard-chartered-manhattan-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "sc-super-value-titanium",
        "bank_name": "Standard Chartered",
        "card_name": "Super Value Titanium",
        "card_type": "lifestyle",
        "joining_fee": 750,
        "annual_fee": 750,
        "is_lifetime_free": False,
        "welcome_benefits": "₹750 voucher",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹75K spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 680,
        "category_bonuses": {"dining": 2.0, "shopping": 1.0},
        "affiliate_link": "https://www.sc.com/in/credit-cards/super-value-titanium-credit-card/",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # HSBC Cards (Already had 1, adding 1 more = 2 total)
    {
        "id": "hsbc-cashback",
        "bank_name": "HSBC",
        "card_name": "Cashback",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 cashback on first transaction",
        "reward_rate": 0.0,
        "cashback_rate": 10.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 1000,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent", "Utilities"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": False,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"online_shopping": 10.0, "groceries": 5.0},
        "affiliate_link": "https://www.hsbc.co.in/credit-cards/products/cashback/",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hsbc-cashback-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "hsbc-premier",
        "bank_name": "HSBC",
        "card_name": "Premier",
        "card_type": "premium",
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹2.5L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.5,
        "lounge_access": "6 domestic & 2 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 100000,
        "min_credit_score": 720,
        "category_bonuses": {"travel": 4.0, "dining": 2.5},
        "affiliate_link": "https://www.hsbc.co.in/credit-cards/products/premier/",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # Yes Bank Cards (Already had 1, adding 1 more = 2 total)
    {
        "id": "yes-marquee",
        "bank_name": "Yes Bank",
        "card_name": "Marquee",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "Club Vistara Gold membership",
        "reward_rate": 6.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Airmiles", "Statement credit", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["₹10,000 voucher on ₹8L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.75,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 12.0, "dining": 6.0, "shopping": 3.0},
        "affiliate_link": "https://www.yesbank.in/personal-banking/cards/credit-cards/yes-marquee-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/yes-bank-marquee-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "yes-prosperity-edge",
        "bank_name": "Yes Bank",
        "card_name": "Prosperity Edge",
        "card_type": "lifestyle",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "500 reward points",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"shopping": 2.0, "dining": 1.5},
        "affiliate_link": "https://www.yesbank.in/personal-banking/cards/credit-cards/yes-prosperity-edge",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # Citi Bank Cards (Already had 1, adding 2 more = 3 total)
    {
        "id": "citi-rewards",
        "bank_name": "Citi Bank",
        "card_name": "Rewards",
        "card_type": "lifestyle",
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "welcome_benefits": "2,500 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit", "Products"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Annual fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 80000,
        "min_credit_score": 680,
        "category_bonuses": {"dining": 5.0, "shopping": 2.0},
        "affiliate_link": "https://www.online.citibank.co.in/products-services/credit-cards/citi-rewards-credit-card.htm",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/citi-rewards-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "citi-cashback",
        "bank_name": "Citi Bank",
        "card_name": "Cashback",
        "card_type": "cashback",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 cashback",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 40000,
        "min_credit_score": 680,
        "category_bonuses": {"online_shopping": 5.0, "groceries": 5.0},
        "affiliate_link": "https://www.online.citibank.co.in/products-services/credit-cards/citi-cashback-credit-card.htm",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # RBL Bank Cards (Already had 1, adding 1 more = 2 total)
    {
        "id": "rbl-shoprite",
        "bank_name": "RBL Bank",
        "card_name": "Shoprite",
        "card_type": "cashback",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 gift voucher",
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": 2000,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel", "Rent"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"groceries": 10.0, "dining": 5.0},
        "affiliate_link": "https://www.rblbank.com/credit-cards/shoprite-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/rbl-shoprite-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "rbl-world-safari",
        "bank_name": "RBL Bank",
        "card_name": "World Safari",
        "card_type": "travel",
        "joining_fee": 3000,
        "annual_fee": 3000,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.0,
        "lounge_access": "8 domestic & 4 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 80000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 5.0, "dining": 2.5},
        "affiliate_link": "https://www.rblbank.com/credit-cards/world-safari-credit-card",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # AU Small Finance Bank Cards (2 cards)
    {
        "id": "au-zenith",
        "bank_name": "AU Small Finance Bank",
        "card_name": "Zenith",
        "card_type": "premium",
        "joining_fee": 3000,
        "annual_fee": 3000,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 60000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 4.0, "dining": 2.0},
        "affiliate_link": "https://www.aubank.in/credit-card/zenith-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/au-zenith-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "au-lit",
        "bank_name": "AU Small Finance Bank",
        "card_name": "LIT",
        "card_type": "lifestyle",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "₹500 voucher",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"online_shopping": 3.0, "movies": 5.0},
        "affiliate_link": "https://www.aubank.in/credit-card/lit-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/au-lit-credit-card.html",
        "paisabazaar_link": None
    },

    # IDFC First Bank Cards (2 cards)
    {
        "id": "idfc-wealth",
        "bank_name": "IDFC First Bank",
        "card_name": "Wealth",
        "card_type": "premium",
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points",
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹5L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 1.99,
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 200000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 6.0, "dining": 3.0},
        "affiliate_link": "https://www.idfcfirstbank.com/credit-card/wealth-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/idfc-first-wealth-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "idfc-select",
        "bank_name": "IDFC First Bank",
        "card_name": "Select",
        "card_type": "lifestyle",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "1,000 reward points",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹50K spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"dining": 3.0, "shopping": 1.0},
        "affiliate_link": "https://www.idfcfirstbank.com/credit-card/select-credit-card",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/idfc-first-select-credit-card.html",
        "paisabazaar_link": None
    },

    # Federal Bank Cards (Already had 1, adding 1 more = 2 total)
    {
        "id": "federal-celesta",
        "bank_name": "Federal Bank",
        "card_name": "Celesta",
        "card_type": "travel",
        "joining_fee": 1500,
        "annual_fee": 1500,
        "is_lifetime_free": False,
        "welcome_benefits": "2 complimentary movie tickets",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.5,
        "redemption_options": ["Airmiles", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹2L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.0,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 60000,
        "min_credit_score": 680,
        "category_bonuses": {"travel": 4.0, "dining": 2.0},
        "affiliate_link": "https://www.federalbank.co.in/credit-cards/celesta",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/federal-celesta-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "federal-scapia",
        "bank_name": "Federal Bank",
        "card_name": "Scapia",
        "card_type": "travel",
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "welcome_benefits": "Welcome bonus on first transaction",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Vouchers"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": [],
        "excluded_categories": ["Fuel"],
        "forex_markup": 0.0,
        "lounge_access": "None",
        "fuel_surcharge_waiver": False,
        "emi_available": True,
        "min_income": 30000,
        "min_credit_score": 650,
        "category_bonuses": {"travel": 5.0, "international": 2.0},
        "affiliate_link": "https://www.federalbank.co.in/scapia",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },

    # Bank of Baroda Cards (2 cards)
    {
        "id": "bob-eterna",
        "bank_name": "Bank of Baroda",
        "card_name": "Eterna",
        "card_type": "premium",
        "joining_fee": 2999,
        "annual_fee": 2999,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹3L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 60000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 3.0, "dining": 2.0},
        "affiliate_link": "https://www.bankofbaroda.in/personal-banking/digital-products/cards/credit-cards/bob-eterna",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/bank-of-baroda-eterna-credit-card.html",
        "paisabazaar_link": None
    },
    {
        "id": "bob-premier",
        "bank_name": "Bank of Baroda",
        "card_name": "Premier",
        "card_type": "lifestyle",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 voucher",
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.25,
        "redemption_options": ["Vouchers", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 3.5,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 35000,
        "min_credit_score": 650,
        "category_bonuses": {"dining": 2.0, "shopping": 1.0},
        "affiliate_link": "https://www.bankofbaroda.in/personal-banking/digital-products/cards/credit-cards/bob-premier",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    }
]

# Total Cards: 50+ cards across all major Indian banks
# Banks covered: HDFC (7), SBI (6), ICICI (6), Axis (6), Amex (4), Kotak (5), IndusInd (4), 
# Standard Chartered (4), HSBC (2), Yes Bank (2), Citi (3), RBL (2), AU Bank (2), IDFC (2), Federal (2), BOB (2)""