# Comprehensive Indian Credit Card Database (50+ cards)

INDIAN_CREDIT_CARDS = [
    # HDFC Bank Cards
    {
        "id": "hdfc-infinia",
        "bank_name": "HDFC Bank",
        "card_name": "Infinia",
        "card_type": "premium",
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "welcome_benefits": "10,000 reward points + complimentary Club Marriott membership",
        "reward_rate": 3.3,
        "cashback_rate": 0.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Travel", "Apple products", "Smartbuy", "Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["10,000 points on ₹8L annual spend"],
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "forex_markup": 2.0,
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 250000,
        "min_credit_score": 750,
        "category_bonuses": {"travel": 5.0, "dining": 3.3, "shopping": 3.3},
        "affiliate_link": "https://bankbazaar.com/hdfc-infinia",
        "bankbazaar_link": "https://bankbazaar.com/hdfc-infinia",
        "paisabazaar_link": "https://paisabazaar.com/hdfc-infinia"
    },
    {
        "id": "hdfc-regalia-gold",
        "bank_name": "HDFC Bank",
        "card_name": "Regalia Gold",
        "card_type": "premium",
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "welcome_benefits": "5,000 reward points",
        "reward_rate": 2.5,
        "cashback_rate": 0.0,
        "redemption_ratio": 0.7,
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "reward_cap_monthly": 15000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["4,000 points on ₹3L annual spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 2.0,
        "lounge_access": "12 domestic per year",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 100000,
        "min_credit_score": 700,
        "category_bonuses": {"travel": 4.0, "dining": 2.5, "shopping": 2.5},
        "affiliate_link": "https://bankbazaar.com/hdfc-regalia",
        "bankbazaar_link": "https://bankbazaar.com/hdfc-regalia",
        "paisabazaar_link": "https://paisabazaar.com/hdfc-regalia"
    },
    {
        "id": "hdfc-millennia",
        "bank_name": "HDFC Bank",
        "card_name": "Millennia",
        "card_type": "lifestyle",
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "welcome_benefits": "1,000 cashback points",
        "reward_rate": 2.5,
        "cashback_rate": 5.0,
        "redemption_ratio": 0.3,
        "redemption_options": ["Cashback", "Vouchers"],
        "reward_cap_monthly": 1000,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹1L spend"],
        "excluded_categories": ["Fuel", "Utilities"],
        "forex_markup": 2.0,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 50000,
        "min_credit_score": 700,
        "category_bonuses": {"online_shopping": 5.0, "groceries": 2.5},
        "affiliate_link": "https://bankbazaar.com/hdfc-millennia",
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },
    {
        "id": "hdfc-freedom",
        "bank_name": "HDFC Bank",
        "card_name": "Freedom",
        "card_type": "cashback",
        "joining_fee": 500,
        "annual_fee": 500,
        "is_lifetime_free": False,
        "welcome_benefits": "₹500 cashback",
        "reward_rate": 0.0,
        "cashback_rate": 1.0,
        "redemption_ratio": 1.0,
        "redemption_options": ["Statement credit"],
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "milestone_benefits": ["Fee waiver on ₹50K spend"],
        "excluded_categories": ["Fuel"],
        "forex_markup": 2.0,
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "emi_available": True,
        "min_income": 25000,
        "min_credit_score": 650,
        "category_bonuses": {"all": 1.0},
        "affiliate_link": None,
        "bankbazaar_link": None,
        "paisabazaar_link": None
    },
]

# Due to size, I'll continue with more cards in the actual implementation
# This shows the structure for 50+ cards
