# Credit Card Database with Extended Fields
# All 16 sections populated with placeholder/sample data
# Admin can update via dashboard

CREDIT_CARDS_DATABASE = [
    {
        "id": "hdfc-infinia",
        "bank_name": "HDFC Bank",
        "card_name": "Infinia",
        "card_network": "Visa",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Rewards", "Lounge"],
        "image_url": None,
        "overall_rating": 4.8,
        
        # Quick Highlights
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "reward_rate": 3.3,
        "cashback_rate": 0.0,
        "value_back_percent": 3.3,
        "lounge_access_summary": "Unlimited domestic & international",
        "forex_markup": 2.0,
        "welcome_bonus_summary": "10,000 reward points + Club Marriott",
        
        # About the Card
        "card_description": "HDFC Infinia is India's most premium credit card offering unmatched rewards and luxury benefits. Perfect for high-net-worth individuals who travel frequently and spend significantly on premium categories.",
        "best_suited_for": ["Frequent travelers", "High spenders (₹10L+/month)", "Luxury seekers", "Business executives"],
        "key_benefits": ["3.3% value back on all spends", "Unlimited airport lounge access", "Golf privileges worldwide", "Concierge services"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        
        # Rewards Program
        "reward_earning": {
            "base_rate": "5 Reward Points per ₹150 spent",
            "base_value": 3.3,
            "category_multipliers": {"SmartBuy": "10X rewards", "Travel": "5X rewards", "Dining": "2X rewards"},
            "partner_portals": ["SmartBuy", "Amazon", "Flipkart"],
            "accelerated_rewards": ["10X on SmartBuy portal", "5X on travel bookings"]
        },
        "reward_redemption": {
            "airmiles_ratio": "1 RP = 1 Air Mile",
            "travel_value": "1 RP = ₹1 on SmartBuy",
            "voucher_value": "1 RP = ₹0.50",
            "cashback_value": "1 RP = ₹0.30",
            "best_redemption": "Air miles or SmartBuy travel",
            "redemption_options": ["Air Miles", "Travel", "Vouchers", "Statement Credit"]
        },
        "redemption_ratio": 1.0,
        "reward_cap_monthly": None,
        "reward_cap_yearly": None,
        "category_bonuses": {"travel": 5.0, "dining": 3.3, "shopping": 3.3},
        "redemption_options": ["Travel", "Apple products", "Smartbuy", "Statement credit"],
        
        # Welcome Benefits
        "welcome_benefits": "10,000 reward points + complimentary Club Marriott membership",
        "welcome_benefits_list": ["10,000 reward points", "Club Marriott membership (₹6,000 value)", "Complimentary golf rounds"],
        "welcome_bonus_conditions": "Complete first transaction within 90 days",
        
        # Milestone Benefits
        "milestone_benefits": ["10,000 points on ₹8L annual spend"],
        "milestone_details": [
            {"spend": "₹8,00,000/year", "benefit": "10,000 bonus points"},
            {"spend": "₹15,00,000/year", "benefit": "Additional 5,000 points + Travel voucher"}
        ],
        
        # Travel Benefits
        "travel_benefits": {
            "domestic_lounge": "Unlimited access via Priority Pass",
            "international_lounge": "Unlimited access via Priority Pass",
            "lounge_network": ["Priority Pass", "Dreamfolks", "Mastercard Lounge"],
            "airport_concierge": True,
            "golf_privileges": "2 complimentary rounds per quarter",
            "airport_transfer": "4 complimentary airport transfers/year",
            "travel_insurance": "Up to ₹3 Crore coverage",
            "forex_markup": 2.0
        },
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        
        # Lifestyle Benefits
        "lifestyle_benefits": {
            "dining_benefits": ["20% off at 1500+ restaurants", "Complimentary Dineout Plus"],
            "entertainment_benefits": ["Buy 1 Get 1 on movies", "Premium event access"],
            "shopping_benefits": ["Extra discounts on SmartBuy", "Early sale access"],
            "brand_partnerships": ["Marriott", "Taj Hotels", "Oberoi Hotels"],
            "memberships": ["Club Marriott", "Amazon Prime (3 months)"]
        },
        
        # Fees and Charges
        "fees_charges": {
            "joining_fee": 12500,
            "annual_fee": 12500,
            "annual_fee_waiver": "Spend ₹8L per year",
            "finance_charges": "3.49% per month",
            "cash_withdrawal_fee": "2.5% or ₹500 min",
            "late_payment_charges": "Up to ₹1,300",
            "forex_markup": "2%",
            "reward_redemption_fee": "Nil"
        },
        "emi_available": True,
        
        # Excluded Categories
        "excluded_categories": ["Fuel", "Utilities", "Rent", "Government payments", "Insurance premium"],
        
        # Eligibility
        "min_income": 250000,
        "min_credit_score": 750,
        "eligibility_criteria": {
            "min_age": 21,
            "max_age": 60,
            "min_income_salaried": 250000,
            "min_income_self_employed": 300000,
            "employment_types": ["Salaried", "Self-Employed", "Business Owner"],
            "min_credit_score": 750,
            "existing_card_required": True,
            "additional_requirements": ["Existing HDFC relationship preferred", "ITR for self-employed"]
        },
        
        # Pros and Cons
        "pros": ["Best-in-class reward rate (3.3%)", "Unlimited lounge access globally", "Premium travel benefits", "No reward cap", "Excellent redemption value"],
        "cons": ["High annual fee (₹12,500)", "Invite-only card", "High income requirement", "Reward points excluded on utilities"],
        
        # Similar Cards
        "similar_cards": ["axis-magnus", "amex-platinum", "hdfc-regalia-gold"],
        
        # Reviews
        "expert_rating": 4.8,
        "expert_review": "HDFC Infinia is the gold standard for premium credit cards in India. With its 3.3% value back and unlimited lounge access, it offers exceptional value for high spenders. The invite-only nature adds exclusivity.",
        "user_reviews": [],
        "category_ratings": {"rewards": 4.9, "travel": 5.0, "lifestyle": 4.5, "fees": 4.0},
        
        # FAQs
        "faqs": [
            {"question": "How to get HDFC Infinia?", "answer": "Infinia is an invite-only card. You need to be an existing HDFC premium customer with high spending pattern."},
            {"question": "What is the best way to redeem points?", "answer": "Air miles conversion and SmartBuy travel bookings offer the best value at 1:1 ratio."},
            {"question": "Is the annual fee waived?", "answer": "Yes, the annual fee is waived if you spend ₹8 lakh or more in a year."},
            {"question": "Does Infinia have lounge access for guests?", "answer": "Yes, you can bring one guest to domestic and international lounges."}
        ],
        
        # Apply Links
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-infinia-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-infinia-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-infinia/",
        "bank_apply_link": "https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-credit-card"
    },
    {
        "id": "hdfc-regalia-gold",
        "bank_name": "HDFC Bank",
        "card_name": "Regalia Gold",
        "card_network": "Visa",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Rewards"],
        "image_url": None,
        "overall_rating": 4.3,
        "joining_fee": 2500,
        "annual_fee": 2500,
        "is_lifetime_free": False,
        "reward_rate": 2.5,
        "cashback_rate": 0.0,
        "value_back_percent": 2.5,
        "lounge_access_summary": "12 domestic lounges per year",
        "forex_markup": 2.0,
        "welcome_bonus_summary": "5,000 reward points",
        "card_description": "HDFC Regalia Gold is a mid-premium card offering good rewards and travel benefits at an affordable annual fee.",
        "best_suited_for": ["Moderate travelers", "Regular spenders", "HDFC customers"],
        "key_benefits": ["2.5% value back", "12 domestic lounge visits", "Travel insurance"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        "reward_earning": {"base_rate": "4 RP per ₹150", "base_value": 2.5},
        "reward_redemption": {"travel_value": "1 RP = ₹0.70", "voucher_value": "1 RP = ₹0.50"},
        "redemption_ratio": 0.7,
        "reward_cap_monthly": 15000,
        "reward_cap_yearly": None,
        "category_bonuses": {"travel": 4.0, "dining": 2.5, "shopping": 2.5},
        "redemption_options": ["Travel", "Vouchers", "Statement credit"],
        "welcome_benefits": "5,000 reward points",
        "welcome_benefits_list": ["5,000 reward points worth ₹3,500"],
        "welcome_bonus_conditions": "On first transaction",
        "milestone_benefits": ["4,000 points on ₹3L annual spend"],
        "milestone_details": [{"spend": "₹3,00,000/year", "benefit": "4,000 bonus points"}],
        "travel_benefits": {"domestic_lounge": "12 visits per year", "international_lounge": "6 visits per year"},
        "lounge_access": "12 domestic per year",
        "fuel_surcharge_waiver": True,
        "lifestyle_benefits": {"dining_benefits": ["15% off at partner restaurants"]},
        "fees_charges": {"joining_fee": 2500, "annual_fee": 2500, "annual_fee_waiver": "Spend ₹3L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Utilities"],
        "min_income": 100000,
        "min_credit_score": 700,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 100000},
        "pros": ["Affordable annual fee", "Good reward rate", "Easy to get"],
        "cons": ["Reward cap exists", "Limited lounge access"],
        "similar_cards": ["hdfc-infinia", "axis-magnus"],
        "expert_rating": 4.3,
        "expert_review": "A solid mid-tier card for HDFC customers seeking rewards and travel benefits.",
        "category_ratings": {"rewards": 4.2, "travel": 4.0, "lifestyle": 4.0},
        "faqs": [{"question": "Is annual fee waived?", "answer": "Yes, on ₹3L annual spend"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-regalia-gold-credit-card.html",
        "bankbazaar_link": "https://www.bankbazaar.com/credit-card/hdfc-bank-regalia-gold-credit-card.html",
        "paisabazaar_link": "https://www.paisabazaar.com/credit-card/hdfc-regalia/"
    },
    {
        "id": "sbi-simplyclick",
        "bank_name": "SBI Card",
        "card_name": "SimplyCLICK",
        "card_network": "Visa",
        "card_type": "cashback",
        "category_tags": ["Cashback", "Shopping", "Online"],
        "image_url": None,
        "overall_rating": 4.2,
        "joining_fee": 499,
        "annual_fee": 499,
        "is_lifetime_free": False,
        "reward_rate": 1.0,
        "cashback_rate": 5.0,
        "value_back_percent": 5.0,
        "lounge_access_summary": "None",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "₹500 Amazon voucher",
        "card_description": "SBI SimplyCLICK is designed for online shoppers, offering 5% cashback on select online partners.",
        "best_suited_for": ["Online shoppers", "Amazon users", "Budget-conscious spenders"],
        "key_benefits": ["5% cashback on partner sites", "10X rewards on online shopping"],
        "spending_categories": ["Online Shopping", "Amazon", "Cleartrip"],
        "reward_earning": {"base_rate": "1 RP per ₹100", "category_multipliers": {"online_shopping": "10X rewards"}},
        "redemption_ratio": 0.25,
        "reward_cap_monthly": 2000,
        "category_bonuses": {"online_shopping": 10.0, "dining": 1.0},
        "redemption_options": ["Amazon vouchers", "Statement credit"],
        "welcome_benefits": "₹500 Amazon voucher",
        "welcome_benefits_list": ["₹500 Amazon voucher on first transaction"],
        "milestone_benefits": ["Annual fee waiver on ₹1L spend"],
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 499, "annual_fee": 499, "annual_fee_waiver": "Spend ₹1L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Utilities", "Rent"],
        "min_income": 30000,
        "min_credit_score": 650,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 30000},
        "pros": ["Low annual fee", "Great for online shopping", "Easy approval"],
        "cons": ["No lounge access", "Low base reward rate"],
        "similar_cards": ["icici-amazon-pay", "axis-ace"],
        "expert_rating": 4.2,
        "category_ratings": {"rewards": 4.0, "shopping": 4.5},
        "faqs": [{"question": "Which sites give 10X rewards?", "answer": "Amazon, Cleartrip, Apollo, Netmeds, and more"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/sbi-simplyclick-credit-card.html"
    },
    {
        "id": "icici-amazon-pay",
        "bank_name": "ICICI Bank",
        "card_name": "Amazon Pay",
        "card_network": "Visa",
        "card_type": "cashback",
        "category_tags": ["Cashback", "Shopping", "Lifetime Free"],
        "image_url": None,
        "overall_rating": 4.5,
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "value_back_percent": 5.0,
        "lounge_access_summary": "None",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "₹500 Amazon voucher",
        "card_description": "The best lifetime free card for Amazon shoppers. Get 5% cashback on Amazon and 2% on other online purchases.",
        "best_suited_for": ["Amazon Prime members", "Online shoppers", "First-time card users"],
        "key_benefits": ["5% on Amazon", "2% on other online", "Lifetime free"],
        "spending_categories": ["Amazon", "Online Shopping"],
        "reward_earning": {"base_rate": "5% on Amazon", "category_multipliers": {"amazon": "5%", "online": "2%", "offline": "1%"}},
        "redemption_ratio": 1.0,
        "reward_cap_yearly": 15000,
        "category_bonuses": {"amazon": 5.0, "online_shopping": 2.0},
        "redemption_options": ["Amazon Pay balance"],
        "welcome_benefits": "₹500 Amazon voucher on first transaction",
        "welcome_benefits_list": ["₹500 Amazon Gift Card"],
        "milestone_benefits": [],
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 0, "annual_fee": 0},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent", "EMI"],
        "min_income": 25000,
        "min_credit_score": 650,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 25000},
        "pros": ["Lifetime free", "5% on Amazon", "Easy approval", "No hidden charges"],
        "cons": ["No lounge access", "Cashback cap exists", "Limited to Amazon Pay redemption"],
        "similar_cards": ["sbi-simplyclick", "axis-ace"],
        "expert_rating": 4.5,
        "category_ratings": {"rewards": 4.5, "shopping": 5.0, "fees": 5.0},
        "faqs": [{"question": "Is it really lifetime free?", "answer": "Yes, there are no hidden charges or annual fees"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/icici-amazon-pay-credit-card.html"
    },
    {
        "id": "axis-magnus",
        "bank_name": "Axis Bank",
        "card_name": "Magnus",
        "card_network": "Visa",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Rewards", "Lounge"],
        "image_url": None,
        "overall_rating": 4.7,
        "joining_fee": 12500,
        "annual_fee": 12500,
        "is_lifetime_free": False,
        "reward_rate": 12.0,
        "cashback_rate": 0.0,
        "value_back_percent": 12.0,
        "lounge_access_summary": "Unlimited domestic, 8 international",
        "forex_markup": 2.0,
        "welcome_bonus_summary": "25,000 Edge Reward points",
        "card_description": "Axis Magnus offers industry-leading 12 Edge Points per ₹200 spent, making it one of the highest rewarding cards in India.",
        "best_suited_for": ["High spenders", "Travel enthusiasts", "Reward maximizers"],
        "key_benefits": ["12% value back on travel", "Unlimited domestic lounges", "Premium concierge"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        "reward_earning": {"base_rate": "12 Edge Points per ₹200", "base_value": 12.0},
        "reward_redemption": {"airmiles_ratio": "1 Edge Point = 1 Airmile", "travel_value": "1 EP = ₹1"},
        "redemption_ratio": 1.0,
        "category_bonuses": {"travel": 12.0, "dining": 12.0, "shopping": 6.0},
        "redemption_options": ["Travel", "Vouchers", "Airmiles"],
        "welcome_benefits": "25,000 Edge Reward points",
        "welcome_benefits_list": ["25,000 Edge Points (₹25,000 value)"],
        "milestone_benefits": ["25,000 points on ₹15L annual spend"],
        "travel_benefits": {"domestic_lounge": "Unlimited", "international_lounge": "8 per year"},
        "lounge_access": "Unlimited domestic & 8 international",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 12500, "annual_fee": 12500},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent"],
        "min_income": 250000,
        "min_credit_score": 750,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 250000},
        "pros": ["Highest reward rate (12%)", "No reward cap", "Unlimited domestic lounge"],
        "cons": ["High annual fee", "High income requirement"],
        "similar_cards": ["hdfc-infinia", "amex-platinum"],
        "expert_rating": 4.7,
        "category_ratings": {"rewards": 5.0, "travel": 4.8, "fees": 3.5},
        "faqs": [{"question": "What's the best redemption?", "answer": "Airmiles and travel bookings at 1:1 value"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/axis-magnus-credit-card.html"
    },
    {
        "id": "amex-platinum",
        "bank_name": "American Express",
        "card_name": "Platinum Card",
        "card_network": "Amex",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Luxury", "Lounge"],
        "image_url": None,
        "overall_rating": 4.6,
        "joining_fee": 60000,
        "annual_fee": 60000,
        "is_lifetime_free": False,
        "reward_rate": 1.0,
        "cashback_rate": 0.0,
        "value_back_percent": 1.0,
        "lounge_access_summary": "Unlimited + Centurion Lounges",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "Taj voucher ₹10,000 + Transfers",
        "card_description": "The Amex Platinum Card is the ultimate luxury card with access to exclusive Centurion Lounges and premium hotel benefits.",
        "best_suited_for": ["Luxury travelers", "Hotel enthusiasts", "UHNW individuals"],
        "key_benefits": ["Centurion Lounge access", "Taj Epicure membership", "Airport transfers"],
        "spending_categories": ["Travel", "Hotels", "Dining"],
        "redemption_ratio": 0.5,
        "category_bonuses": {"travel": 5.0, "dining": 2.0, "hotels": 5.0},
        "redemption_options": ["Travel", "Hotels", "Statement credit"],
        "welcome_benefits": "Taj voucher worth ₹10,000 + Airport transfers",
        "welcome_benefits_list": ["₹10,000 Taj voucher", "4 airport transfers", "Marriott Gold status"],
        "milestone_benefits": ["Taj vouchers on milestone spend"],
        "travel_benefits": {"domestic_lounge": "Unlimited", "international_lounge": "Unlimited + Centurion"},
        "lounge_access": "Unlimited domestic & international + guest + Centurion lounges",
        "fuel_surcharge_waiver": True,
        "lifestyle_benefits": {"memberships": ["Taj Epicure", "Marriott Gold", "Hilton Gold"]},
        "fees_charges": {"joining_fee": 60000, "annual_fee": 60000},
        "emi_available": True,
        "excluded_categories": [],
        "min_income": 500000,
        "min_credit_score": 800,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 500000},
        "pros": ["Centurion Lounge access", "Hotel status benefits", "Premium lifestyle"],
        "cons": ["Very high annual fee", "Limited acceptance in India", "Low reward rate"],
        "similar_cards": ["hdfc-infinia", "axis-magnus"],
        "expert_rating": 4.6,
        "category_ratings": {"rewards": 3.5, "travel": 5.0, "lifestyle": 5.0, "fees": 2.5},
        "faqs": [{"question": "Is Amex accepted everywhere?", "answer": "No, acceptance is limited compared to Visa/Mastercard"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/american-express-platinum-card.html"
    },
    {
        "id": "axis-ace",
        "bank_name": "Axis Bank",
        "card_name": "Ace",
        "card_network": "Visa",
        "card_type": "cashback",
        "category_tags": ["Cashback", "Lifetime Free", "Google Pay"],
        "image_url": None,
        "overall_rating": 4.4,
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "value_back_percent": 5.0,
        "lounge_access_summary": "None",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "₹500 cashback on ₹10K spend",
        "card_description": "Axis Ace is the best lifetime free card for Google Pay users, offering 5% cashback on bill payments via Google Pay.",
        "best_suited_for": ["Google Pay users", "Bill payment enthusiasts", "First-time card users"],
        "key_benefits": ["5% on Google Pay", "2% on utilities", "Lifetime free"],
        "spending_categories": ["Bill Payments", "Google Pay", "Utilities"],
        "redemption_ratio": 1.0,
        "reward_cap_yearly": 15000,
        "category_bonuses": {"google_pay": 5.0, "utilities": 2.0},
        "redemption_options": ["Statement credit"],
        "welcome_benefits": "₹500 cashback on ₹10,000 spend in 45 days",
        "milestone_benefits": [],
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 0, "annual_fee": 0},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent", "Wallet loads"],
        "min_income": 20000,
        "min_credit_score": 600,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 20000},
        "pros": ["Lifetime free", "Great for bill payments", "Easy approval"],
        "cons": ["No lounge access", "Limited category benefits"],
        "similar_cards": ["icici-amazon-pay", "sbi-simplyclick"],
        "expert_rating": 4.4,
        "category_ratings": {"rewards": 4.3, "fees": 5.0},
        "faqs": [{"question": "Which payments give 5%?", "answer": "Bill payments via Google Pay including electricity, mobile, DTH"}],
        "affiliate_link": "https://www.bankbazaar.com/credit-card/axis-ace-credit-card.html"
    },
    {
        "id": "indusind-legend",
        "bank_name": "IndusInd Bank",
        "card_name": "Legend",
        "card_network": "Mastercard",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Golf"],
        "image_url": None,
        "overall_rating": 4.3,
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "value_back_percent": 3.0,
        "lounge_access_summary": "Unlimited domestic & international",
        "forex_markup": 1.75,
        "welcome_bonus_summary": "₹25,000 welcome vouchers + Golf",
        "card_description": "IndusInd Legend offers excellent travel benefits with one of the lowest forex markups in the industry.",
        "best_suited_for": ["International travelers", "Golf enthusiasts", "Forex spenders"],
        "key_benefits": ["1.75% forex markup", "Unlimited lounge access", "Golf privileges"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        "redemption_ratio": 1.0,
        "category_bonuses": {"travel": 5.0, "dining": 3.0, "shopping": 3.0},
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "welcome_benefits": "₹25,000 welcome vouchers + Golf rounds",
        "milestone_benefits": ["Annual fee waiver on ₹8L spend"],
        "travel_benefits": {"domestic_lounge": "Unlimited", "international_lounge": "Unlimited", "forex_markup": 1.75},
        "lounge_access": "Unlimited domestic & international + guest",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 10000, "annual_fee": 10000, "forex_markup": "1.75%"},
        "emi_available": True,
        "excluded_categories": ["Fuel"],
        "min_income": 200000,
        "min_credit_score": 750,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 200000},
        "pros": ["Lowest forex markup", "Unlimited lounge access", "Golf benefits"],
        "cons": ["Limited brand awareness", "High annual fee"],
        "similar_cards": ["hdfc-infinia", "axis-magnus"],
        "expert_rating": 4.3,
        "category_ratings": {"rewards": 4.0, "travel": 4.8, "forex": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/indusind-legend-credit-card.html"
    },
    {
        "id": "sc-ultimate",
        "bank_name": "Standard Chartered",
        "card_name": "Ultimate",
        "card_network": "Visa",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Rewards"],
        "image_url": None,
        "overall_rating": 4.1,
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "reward_rate": 3.0,
        "cashback_rate": 0.0,
        "value_back_percent": 3.0,
        "lounge_access_summary": "Unlimited domestic, 6 international",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "10,000 reward points",
        "card_description": "A well-balanced premium card with good rewards and travel benefits at a moderate annual fee.",
        "best_suited_for": ["Moderate spenders", "SC customers", "Travel enthusiasts"],
        "key_benefits": ["3% rewards", "Good lounge access", "Annual fee waiver available"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        "redemption_ratio": 0.8,
        "category_bonuses": {"travel": 5.0, "dining": 5.0, "shopping": 1.5},
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "welcome_benefits": "10,000 reward points",
        "milestone_benefits": ["Annual fee waiver on ₹4L spend"],
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 5000, "annual_fee": 5000, "annual_fee_waiver": "Spend ₹4L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Utilities"],
        "min_income": 150000,
        "min_credit_score": 720,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 150000},
        "pros": ["Moderate annual fee", "Good rewards", "Easy fee waiver"],
        "cons": ["Lower redemption value", "Limited international lounges"],
        "similar_cards": ["hdfc-regalia-gold"],
        "expert_rating": 4.1,
        "category_ratings": {"rewards": 4.0, "travel": 4.0, "fees": 4.2},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/standard-chartered-ultimate-credit-card.html"
    },
    {
        "id": "hsbc-cashback",
        "bank_name": "HSBC",
        "card_name": "Cashback",
        "card_network": "Visa",
        "card_type": "cashback",
        "category_tags": ["Cashback", "Lifetime Free", "Shopping"],
        "image_url": None,
        "overall_rating": 4.0,
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "reward_rate": 0.0,
        "cashback_rate": 10.0,
        "value_back_percent": 10.0,
        "lounge_access_summary": "None",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "₹500 cashback on first transaction",
        "card_description": "HSBC Cashback offers industry-leading 10% cashback on online shopping and 5% on groceries.",
        "best_suited_for": ["Online shoppers", "Grocery buyers", "Budget-conscious users"],
        "key_benefits": ["10% online cashback", "5% grocery cashback", "Lifetime free"],
        "spending_categories": ["Online Shopping", "Groceries"],
        "redemption_ratio": 1.0,
        "reward_cap_monthly": 1000,
        "category_bonuses": {"online_shopping": 10.0, "groceries": 5.0},
        "redemption_options": ["Statement credit"],
        "welcome_benefits": "₹500 cashback on first transaction",
        "milestone_benefits": [],
        "lounge_access": "None",
        "fuel_surcharge_waiver": False,
        "fees_charges": {"joining_fee": 0, "annual_fee": 0},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent", "Utilities"],
        "min_income": 50000,
        "min_credit_score": 700,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 50000},
        "pros": ["Highest cashback rate", "Lifetime free", "Simple and straightforward"],
        "cons": ["Low monthly cap", "No lounge access", "No fuel surcharge waiver"],
        "similar_cards": ["icici-amazon-pay", "axis-ace"],
        "expert_rating": 4.0,
        "category_ratings": {"rewards": 4.2, "shopping": 4.5, "fees": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/hsbc-cashback-credit-card.html"
    },
    {
        "id": "kotak-white-reserve",
        "bank_name": "Kotak Mahindra Bank",
        "card_name": "White Reserve",
        "card_network": "Visa",
        "card_type": "premium",
        "category_tags": ["Premium", "Rewards", "Travel"],
        "image_url": None,
        "overall_rating": 4.0,
        "joining_fee": 5000,
        "annual_fee": 5000,
        "is_lifetime_free": False,
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "value_back_percent": 2.0,
        "lounge_access_summary": "8 domestic, 4 international",
        "forex_markup": 2.5,
        "welcome_bonus_summary": "10,000 reward points",
        "card_description": "Kotak White Reserve is a solid premium card for Kotak customers with decent rewards and travel benefits.",
        "best_suited_for": ["Kotak customers", "Moderate travelers", "Dining enthusiasts"],
        "key_benefits": ["4% on dining", "Good lounge access", "Reasonable fee"],
        "spending_categories": ["Dining", "Travel", "Shopping"],
        "redemption_ratio": 0.5,
        "category_bonuses": {"dining": 4.0, "travel": 3.0, "shopping": 2.0},
        "redemption_options": ["Airmiles", "Vouchers", "Statement credit"],
        "welcome_benefits": "10,000 reward points",
        "milestone_benefits": ["Annual fee reversal on ₹4L spend"],
        "lounge_access": "8 domestic & 4 international per year",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 5000, "annual_fee": 5000, "annual_fee_waiver": "Spend ₹4L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent"],
        "min_income": 120000,
        "min_credit_score": 700,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 120000},
        "pros": ["Good dining rewards", "Affordable fee", "Easy fee waiver"],
        "cons": ["Lower redemption value", "Limited lounge access"],
        "similar_cards": ["hdfc-regalia-gold", "sc-ultimate"],
        "expert_rating": 4.0,
        "category_ratings": {"rewards": 3.8, "dining": 4.5, "travel": 4.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/kotak-white-reserve-credit-card.html"
    },
    {
        "id": "citi-rewards",
        "bank_name": "Citi Bank",
        "card_name": "Rewards",
        "card_network": "Mastercard",
        "card_type": "rewards",
        "category_tags": ["Rewards", "Dining", "Shopping"],
        "image_url": None,
        "overall_rating": 3.8,
        "joining_fee": 1000,
        "annual_fee": 1000,
        "is_lifetime_free": False,
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "value_back_percent": 2.0,
        "lounge_access_summary": "4 domestic per year",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "2,500 reward points",
        "card_description": "Citi Rewards is an entry-level card with 10X rewards on select categories.",
        "best_suited_for": ["Entry-level users", "Department store shoppers", "Dining enthusiasts"],
        "key_benefits": ["10X on dining", "10X on shopping categories", "Low annual fee"],
        "spending_categories": ["Dining", "Shopping"],
        "redemption_ratio": 0.25,
        "category_bonuses": {"dining": 5.0, "shopping": 2.0},
        "redemption_options": ["Vouchers", "Statement credit", "Products"],
        "welcome_benefits": "2,500 reward points",
        "milestone_benefits": ["Annual fee waiver on ₹3L spend"],
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 1000, "annual_fee": 1000, "annual_fee_waiver": "Spend ₹3L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel"],
        "min_income": 80000,
        "min_credit_score": 680,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 80000},
        "pros": ["Low annual fee", "Good dining rewards", "Easy approval"],
        "cons": ["Low redemption value", "Limited lounge access"],
        "similar_cards": ["kotak-white-reserve"],
        "expert_rating": 3.8,
        "category_ratings": {"rewards": 3.5, "dining": 4.2, "fees": 4.5},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/citi-rewards-credit-card.html"
    },
    {
        "id": "yes-marquee",
        "bank_name": "Yes Bank",
        "card_name": "Marquee",
        "card_network": "Mastercard",
        "card_type": "premium",
        "category_tags": ["Travel", "Premium", "Rewards"],
        "image_url": None,
        "overall_rating": 4.2,
        "joining_fee": 10000,
        "annual_fee": 10000,
        "is_lifetime_free": False,
        "reward_rate": 6.0,
        "cashback_rate": 0.0,
        "value_back_percent": 6.0,
        "lounge_access_summary": "Unlimited domestic, 6 international",
        "forex_markup": 1.75,
        "welcome_bonus_summary": "Club Vistara Gold membership",
        "card_description": "Yes Marquee offers excellent value with high rewards and one of the lowest forex markups.",
        "best_suited_for": ["Travel enthusiasts", "Vistara flyers", "Forex spenders"],
        "key_benefits": ["6% rewards on travel", "Club Vistara Gold", "Low forex markup"],
        "spending_categories": ["Travel", "Dining", "Shopping"],
        "redemption_ratio": 1.0,
        "category_bonuses": {"travel": 12.0, "dining": 6.0, "shopping": 3.0},
        "redemption_options": ["Airmiles", "Statement credit", "Vouchers"],
        "welcome_benefits": "Club Vistara Gold membership",
        "milestone_benefits": ["₹10,000 voucher on ₹8L spend"],
        "lounge_access": "Unlimited domestic & 6 international",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 10000, "annual_fee": 10000, "forex_markup": "1.75%"},
        "emi_available": True,
        "excluded_categories": ["Fuel"],
        "min_income": 250000,
        "min_credit_score": 750,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 250000},
        "pros": ["High reward rate", "Low forex markup", "Club Vistara Gold"],
        "cons": ["Bank stability concerns", "High annual fee"],
        "similar_cards": ["axis-magnus", "indusind-legend"],
        "expert_rating": 4.2,
        "category_ratings": {"rewards": 4.5, "travel": 4.5, "forex": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/yes-bank-marquee-credit-card.html"
    },
    {
        "id": "rbl-shoprite",
        "bank_name": "RBL Bank",
        "card_name": "Shoprite",
        "card_network": "Mastercard",
        "card_type": "cashback",
        "category_tags": ["Cashback", "Lifetime Free", "Groceries"],
        "image_url": None,
        "overall_rating": 3.9,
        "joining_fee": 0,
        "annual_fee": 0,
        "is_lifetime_free": True,
        "reward_rate": 0.0,
        "cashback_rate": 5.0,
        "value_back_percent": 5.0,
        "lounge_access_summary": "None",
        "forex_markup": 3.5,
        "welcome_bonus_summary": "₹500 gift voucher",
        "card_description": "RBL Shoprite is perfect for grocery and dining spenders with its lifetime free and high cashback.",
        "best_suited_for": ["Grocery shoppers", "Dining enthusiasts", "Budget-conscious users"],
        "key_benefits": ["10% on groceries", "5% on dining", "Lifetime free"],
        "spending_categories": ["Groceries", "Dining"],
        "redemption_ratio": 1.0,
        "reward_cap_monthly": 2000,
        "category_bonuses": {"groceries": 10.0, "dining": 5.0},
        "redemption_options": ["Statement credit"],
        "welcome_benefits": "₹500 gift voucher",
        "milestone_benefits": [],
        "lounge_access": "None",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 0, "annual_fee": 0},
        "emi_available": True,
        "excluded_categories": ["Fuel", "Rent"],
        "min_income": 30000,
        "min_credit_score": 650,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 30000},
        "pros": ["Lifetime free", "High grocery cashback", "Easy approval"],
        "cons": ["Low cashback cap", "No lounge access"],
        "similar_cards": ["hsbc-cashback", "icici-amazon-pay"],
        "expert_rating": 3.9,
        "category_ratings": {"rewards": 4.0, "groceries": 4.8, "fees": 5.0},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/rbl-shoprite-credit-card.html"
    },
    {
        "id": "federal-celesta",
        "bank_name": "Federal Bank",
        "card_name": "Celesta",
        "card_network": "Visa",
        "card_type": "travel",
        "category_tags": ["Travel", "Rewards", "Movies"],
        "image_url": None,
        "overall_rating": 3.7,
        "joining_fee": 1500,
        "annual_fee": 1500,
        "is_lifetime_free": False,
        "reward_rate": 2.0,
        "cashback_rate": 0.0,
        "value_back_percent": 2.0,
        "lounge_access_summary": "4 domestic per year",
        "forex_markup": 3.0,
        "welcome_bonus_summary": "2 complimentary movie tickets",
        "card_description": "Federal Celesta is an affordable travel card with decent rewards and movie benefits.",
        "best_suited_for": ["Federal Bank customers", "Movie buffs", "Occasional travelers"],
        "key_benefits": ["Movie tickets", "Travel rewards", "Low annual fee"],
        "spending_categories": ["Travel", "Dining"],
        "redemption_ratio": 0.5,
        "category_bonuses": {"travel": 4.0, "dining": 2.0},
        "redemption_options": ["Airmiles", "Vouchers"],
        "welcome_benefits": "2 complimentary movie tickets",
        "milestone_benefits": ["Fee waiver on ₹2L spend"],
        "lounge_access": "4 domestic per year",
        "fuel_surcharge_waiver": True,
        "fees_charges": {"joining_fee": 1500, "annual_fee": 1500, "annual_fee_waiver": "Spend ₹2L/year"},
        "emi_available": True,
        "excluded_categories": ["Fuel"],
        "min_income": 60000,
        "min_credit_score": 680,
        "eligibility_criteria": {"min_age": 21, "max_age": 60, "min_income_salaried": 60000},
        "pros": ["Low annual fee", "Movie benefits", "Easy fee waiver"],
        "cons": ["Low redemption value", "Limited lounge access"],
        "similar_cards": ["citi-rewards"],
        "expert_rating": 3.7,
        "category_ratings": {"rewards": 3.5, "entertainment": 4.0, "fees": 4.5},
        "affiliate_link": "https://www.bankbazaar.com/credit-card/federal-celesta-credit-card.html"
    }
]
